redis:
  image: redis
  ports:
    - "6379:6379"
elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - "/var/lib/elasticsearch:/var/lib/elasticsearch"
logstash:
  image: deviantony/elk-logstash
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
    - redis
kibana3:
  image: deviantony/elk-kibana:kibana3
  ports:
    - "8080:80"
  links:
    - elasticsearch
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
